language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
services:
  - mongodb
script:
  - yarn
  - yarn lint
  - cd Backend 
  - yarn
  - yarn test
  - cd ../frontend
  - yarn
  - yarn flow
  - yarn test